USE [BD_DOACAO]
GO

/**
Banco: BD_DOACAO
Date: 29/08/2016	
**/

ALTER PROCEDURE VerificarSenhaUsuario
(
	 @USUARIO varchar(30),
     @TIPO_USUARIO varchar(3),
	 @SENHA varchar(30)
)
AS 
BEGIN
	
	DECLARE @SENHA_BINARIA varbinary(100)
	DECLARE @SENHA_CONFERIDA INT

	SELECT @SENHA_BINARIA = SENHA
		FROM TB_CD_USUARIO_USA WITH(NOLOCK)
			WHERE USUARIO = @USUARIO
			AND  TIPO_USUARIO = @TIPO_USUARIO

	-- VALIDAÇÃO.
	SET @SENHA_CONFERIDA =	pwdCompare(@SENHA, @SENHA_BINARIA, 0) 
	
	-- RETORNO.
	SELECT  
		CASE @TIPO_USUARIO
			WHEN 'DOA' THEN ID_DOA
			WHEN 'UHP' THEN ID_UHP
			WHEN  'LAB' THEN ID_LAB
		END AS ID_USUARIO,
		@SENHA_CONFERIDA AS SENHA_CONFERIDA 
	FROM [BD_DOACAO].[dbo].[TB_CD_USUARIO_USA]
	WHERE USUARIO = @USUARIO
	AND  TIPO_USUARIO = @TIPO_USUARIO

	
END 
GO 
