USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_LOG_APLICACAO_LOG]    Script Date: 09/08/2016 22:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_LOG_APLICACAO_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPO_LOG] [varchar](50) NOT NULL,
	[MENSAGEM] [varchar](255) NOT NULL,
	[DATA_CRIACAO] DATETIME
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



