USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_USUARIO_USA] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_USUARIO_USA](
	[USUARIO] [varchar](30) NOT NULL,
	[SENHA][varbinary](100) NOT NULL,
	[TIPO_USUARIO] [varchar](3) NOT NULL,
	[ID_DOA] [int] NULL,
	[ID_UHP] [int] NULL,
	[ID_LAB] [int] NULL)
	
SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CD_USUARIO_USA]  WITH CHECK ADD FOREIGN KEY([ID_DOA])
REFERENCES [dbo].[TB_CD_DOADOR_DOA] ([ID])
GO


ALTER TABLE [dbo].[TB_CD_USUARIO_USA]  WITH CHECK ADD FOREIGN KEY([ID_LAB])
REFERENCES [dbo].[TB_CD_LABORATORIO_CONVENIADO_LAB] ([ID])
GO

ALTER TABLE [dbo].[TB_CD_USUARIO_USA]  WITH CHECK ADD FOREIGN KEY([ID_UHP])
REFERENCES [dbo].[TB_CD_UNIDADE_HOSPITALAR_UHP] ([ID])
GO



