USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_DOADOR_DOA]    Script Date: 31/07/2016 19:58:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_DOADOR_DOA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](255) NOT NULL,
	[SOBRENOME] [varchar](255) NOT NULL,
	[SEXO] [char](1) NOT NULL,
	[CPF] [bigint] NOT NULL,
	[CIDADE] [varchar](50) NULL,
	[ESTADO] [varchar](50) NULL,
	[BAIRRO] [varchar](50) NULL,
	[COMPLEMENTO] [varchar](50) NULL,
	[CEP] [varchar](50) NOT NULL,
	[EMAIL] [varchar](50) NULL,
	[TELEFONE] [varchar](50) NULL,
	[CELULAR] [varchar](50) NULL,
	[TIPO_SANGUINEO] [char](1) NOT NULL,
	[FATOR_RH] [char](1) NOT NULL,
	[DOADOR_DE_SANGUE] [bit] NULL,
	[ULTIMA_DOACAO] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


