USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD]    Script Date: 31/07/2016 19:58:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_LAB] [int] NOT NULL,
	[ID_DOA] [int] NOT NULL,
	[ID_AGL] [int] NOT NULL,
	[CANCELADO] [bit] NOT NULL,
	[MOTIVO_CANCELAMENTO] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD]  WITH CHECK ADD FOREIGN KEY([ID_DOA])
REFERENCES [dbo].[TB_CD_DOADOR_DOA] ([ID])
GO

ALTER TABLE [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD]  WITH CHECK ADD FOREIGN KEY([ID_LAB])
REFERENCES [dbo].[TB_CD_LABORATORIO_CONVENIADO_LAB] ([ID])
GO

ALTER TABLE [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD]  WITH CHECK ADD FOREIGN KEY([ID_AGL])
REFERENCES [dbo].[TB_CD_AGENDA_LABORATORIO_AGL] ([ID])
GO


