USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_SOLICITACAO_BOLSA_DE_SANGUE_BDS]    Script Date: 07/08/2016 18:23:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_SOLICITACAO_BOLSA_DE_SANGUE_BDS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_UHP] [int] NOT NULL,
	[ID_LAB] [int] NOT NULL,
	[ID_PAC] [int] NOT NULL,
	[MOTIVO_DOACAO] [varchar](255) NOT NULL,
	[DIAGNOSTICO] [varchar](255) NOT NULL,
	[DATA_SOLICITACAO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CD_SOLICITACAO_BOLSA_DE_SANGUE_BDS]  WITH CHECK ADD FOREIGN KEY([ID_LAB])
REFERENCES [dbo].[TB_CD_LABORATORIO_CONVENIADO_LAB] ([ID])
GO

ALTER TABLE [dbo].[TB_CD_SOLICITACAO_BOLSA_DE_SANGUE_BDS]  WITH CHECK ADD FOREIGN KEY([ID_PAC])
REFERENCES [dbo].[TB_CD_PACIENTE_PAC] ([ID])
GO

ALTER TABLE [dbo].[TB_CD_SOLICITACAO_BOLSA_DE_SANGUE_BDS]  WITH CHECK ADD FOREIGN KEY([ID_UHP])
REFERENCES [dbo].[TB_CD_UNIDADE_HOSPITALAR_UHP] ([ID])
GO


