USE [BD_DOACAO]
GO

/****** Object:  Table [dbo].[TB_CD_EXAME_EXA]    Script Date: 09/08/2016 20:58:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CD_EXAME_EXA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [int] NOT NULL,
	[NOME] [varchar](255) NOT NULL,
	[VALOR] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


