USE [BD_DOACAO]
GO

/**
Banco: BD_DOACAO
Date: 04/08/2016	
**/

ALTER PROCEDURE ObterAgendaDoador
(
	@ID_DOA int
)
AS
BEGIN
	SELECT AGD.[ID]
		  ,AGD.[ID_LAB]
		  ,LAB.[NOME]
		  ,AGD.[ID_DOA]
		  ,AGD.[ID_AGL]
		  ,AGL.[DATA]
		  ,AGL.[HORA]
		  ,AGD.[CANCELADO]
		  ,AGD.[MOTIVO_CANCELAMENTO]
	  FROM [dbo].[TB_CD_AGENDAMENTO_DOADOR_AGD] AGD WITH(NOLOCK)
		INNER JOIN [dbo].[TB_CD_AGENDA_LABORATORIO_AGL] AGL WITH(NOLOCK)
	  ON AGD.ID_AGL = AGL.ID
		INNER JOIN [dbo].[TB_CD_LABORATORIO_CONVENIADO_LAB] LAB WITH(NOLOCK)
	  ON AGD. ID_LAB = LAB.ID
	  WHERE [ID_DOA] = @ID_DOA 
END
GO



