USE [BD_DOACAO]
GO

/**
Banco: BD_DOACAO
Date: 29/08/2016	
**/

ALTER PROCEDURE VerificarSenhaUsuario
(
	 @USUARIO varchar(30),
     @TIPO_USUARIO varchar(3),
	 @SENHA varchar(30)
)
AS 
BEGIN
	
	DECLARE @SENHA_BINARIA varbinary(100)

	SELECT @SENHA_BINARIA = SENHA
		FROM TB_CD_USUARIO_USA WITH(NOLOCK)
			WHERE USUARIO = @USUARIO
			AND  TIPO_USUARIO = @TIPO_USUARIO

	-- RETORNO
	SELECT pwdCompare(@SENHA, @SENHA_BINARIA, 0) AS CONFERIR_SENHA

END 
GO 
